$(document).ready(function(){
  $("#title").delay( 800 ).fadeIn();
  $("#b1").click(function(){
    $("#q1").toggle();
  });
  $("#b2").click(function(){
    $("#q2").toggle();
  });
  $("#b3").click(function(){
    $("#q3").toggle();
  });
  $("#b4").click(function(){
    $("#q4").toggle();
  });
  $("#b5").click(function(){
    $("#q5").toggle();
  });
  $("#b6").click(function(){
    $("#q6").toggle();
  });
  $("#b7").click(function(){
    $("#q7").toggle();
    });
  $("#b8").click(function(){
    $("#q8").toggle();
    });
  $("#b9").click(function(){
    $("#q9").toggle();
    });
  $("#b10").click(function(){
    $("#q10").toggle();
  });
  $("#b11").click(function(){
    $("#q11").toggle();
  });
  $("#b12").click(function(){
    $("#q12").toggle();
  });
  $("#b13").click(function(){
    $("#q13").toggle();
  });
  $("#b14").click(function(){
    $("#q14").toggle();
  });
  $("#b15").click(function(){
    $("#q15").toggle();
  });
});
